### ISSUE TITLE
TroisJS and Vite SSG

### ISSUE THREAD

**Issue by StevenJPx2** [troisjs/trois#107]
TroisJS doesn't seem to build with Vite-ssg.

```sh
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/stevenjohn/Documents/Projects/SAFT/website-v2/node_modules/three/examples/jsm/controls/OrbitControls.js from /Users/stevenjohn/Documents/Projects/SAFT/website-v2/node_modules/troisjs/build/trois.js not supporte
d.
Instead change the require of OrbitControls.js in /Users/stevenjohn/Documents/Projects/SAFT/website-v2/node_modules/troisjs/build/trois.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/stevenjohn/Documents/Projects/SAFT/website-v2/node_modules/troisjs/build/trois.js:7:24)
    at Module.<anonymous> (/Users/stevenjohn/Documents/Projects/SAFT/website-v2/.vite-ssg-temp/main.js:22:15)
    at build (/Users/stevenjohn/Documents/Projects/SAFT/website-v2/node_modules/vite-ssg/dist/node/cli.js:170:52)
    at async Object.handler (/Users/stevenjohn/Documents/Projects/SAFT/website-v2/node_modules/vite-ssg/dist/node/cli.js:270:3) {
  code: 'ERR_REQUIRE_ESM'
```

The normal Vite build works fine though.

Tauri had this issue as well which had a one-line fix:   https://github.com/tauri-apps/tauri/issues/1625.

**Comment by klevron** [comment]
You have to use TroisJS only on client side, here is an example with nuxt3 : https://github.com/troisjs/nuxt3-test

**Comment by StevenJPx2** [comment]
I had tried that, but it didn't work. The same error shows up.

**Comment by klevron** [comment]
Please check you register component only on client side.
Example with nuxt3 : https://github.com/troisjs/nuxt3-test/blob/master/plugins/test.client.js
