### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by SaFrMo** [troisjs/trois#5]
Absolutely love the idea of this repo, really excited to learn more about it! I'm running into this error when running `yarn && yarn dev`:

```
% yarn dev
yarn run v1.22.10
$ vite
error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  index.3540f44e.js (imported by /[...]/trois/docs/index.html)

Are they installed?
    at optimizeDeps (/[...]/trois/node_modules/vite/dist/node/chunks/dep-d13406fa.js:67493:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOptimize (/[...]/trois/node_modules/vite/dist/node/chunks/dep-d13406fa.js:68030:48)
    at async Server.httpServer.listen (/[...]/trois/node_modules/vite/dist/node/chunks/dep-d13406fa.js:68044:17)
error Command failed with exit code 1.
```

Any thoughts on what the issue might be? Thanks so much!

**Comment by SaFrMo** [comment]
Found the issue - it was just a missing `./` in the JS path in the docs index.html. Submitted PR #6 to solve the issue - thanks!

**Comment by klevron** [comment]
I use docs folder for github page, you can simply delete it
